version: "3.7"

services:
  app:
    build:
      context: .
    volumes:
    - ./backend:/app
    env_file:
      - .env
      - .env.db
    restart: on-failure
    depends_on:
      - db
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
  db:
    image: mysql:8.0
    ports:
    - 3308:3306
    env_file:
      - .env.db
    restart: on-failure
    volumes:
    - ./db_django:/var/lib/mysql

  web:
    image: nginx:alpine
    ports:
    - "80:80"
    links:
      - app
    volumes:
      - ./build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf