# Generated by Django 3.1.4 on 2021-01-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='category',
            field=models.CharField(choices=[('Shirts', 'Shirts'), ('Pants', 'Pants'), ('Dress', 'Dress')], default='Shirts', max_length=50),
        ),
    ]
