# Generated by Django 3.1.4 on 2021-01-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210130_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='brand',
            field=models.CharField(choices=[('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Lacoste', 'Lacoste'), ('Puma', 'Puma'), ('Dior', 'Dior'), ('Chanel', 'Chanel'), ('Gucci', 'Gucci')], default='Adidas', max_length=62),
        ),
    ]
