# Generated by Django 3.1.4 on 2021-01-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210130_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='sex',
            field=models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman')], default='Man', max_length=62),
        ),
    ]
