# Generated by Django 3.1.4 on 2021-01-12 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('order', '0002_ordermodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='shipping_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_address', to='address.shippingaddressmodel'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
