# Generated by Django 3.1.4 on 2021-01-12 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('order', '0005_auto_20210112_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='shipping_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_address', to='address.shippingaddressmodel'),
        ),
    ]
