# Generated by Django 3.1.4 on 2021-01-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('order', '0013_auto_20210114_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='order_items',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='order_items',
            field=models.ManyToManyField(related_name='order', to='cart.CartItemsModel'),
        ),
    ]
